name: 打包EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置Python 3.8.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.8.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 打包成EXE
        run: pyinstaller -F -w XL008-FT1-PAT-V9-FC-V2.py

      - name: 下载EXE
        uses: actions/upload-artifact@v4
        with:
          name: my-windows-exe
          path: dist/*.exe
